# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 565f98198994be56175cb126ba1ae324f7e00d58d0d95b72bf5e9d9d912b2a66d24847fa191d57727ca706fb206f180f603ac98115d3dfd7631aa065b39b2e30

test:
  secret_key_base: 177b36880065948dd62d90894b702ab2be9131fde385437cbe1c9228cadc521905d62856a8e8b432efd6c3794d525e6c71006f374d2ef1ff7544d9aed9eb7c34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
